#[derive(Debug)]
pub enum Instruction {
    BRK, STA, JMP,
    ORA, LDX, LDY,
    LDA, STX, STY,
    SEC, EOR, ADC,
    SBC, NOP, PHA,
    BEQ, BMI, JSR,
    CMP, BNE, RTS,
    SEI, CLD, TXS,
    BPL, BCS, CLC,
    BCC, BIT, BVS,
    BVC, SED, PHP,
    PLA, AND, PLP,
    CLV, CPY, CPX,
    INY, INX, DEY,
    DEX, TAY, TAX,
    TYA, TXA, TSX,
    RTI, LSR, ASL,
    ROR, ROL, INC,
    DEC, RRA,

    // unofficial
    LAX, AAX, DCP,
    ISC, SLO, RLA,
    SRE, KIL, DOP,
}

#[derive(Debug)]
pub enum OpInput {
    UseImplied,
    UseImmediate(u8),
    UseRelative(u16),
    UseAddress(u16),
}

#[derive(Copy, Clone)]
pub enum AddressingMode {
    IMP,
    IMM,
    ZP0,
    ZPX,
    ZPY,
    REL,
    ABS,
    ABX,
    ABY,
    IND,
    IZX,
    IZY,
    ACC,
    BuggyIndirect,
}

impl AddressingMode {
    pub const fn extra_bytes(self) -> u16 {
        match self {
            AddressingMode::ACC => 0,
            AddressingMode::IMP => 0,
            AddressingMode::IMM => 1,
            AddressingMode::ZP0 => 1,
            AddressingMode::ZPX => 1,
            AddressingMode::ZPY => 1,
            AddressingMode::REL => 1,
            AddressingMode::ABS => 2,
            AddressingMode::ABX => 2,
            AddressingMode::ABY => 2,
            AddressingMode::IND => 2,
            AddressingMode::IZX => 1,
            AddressingMode::IZY => 1,
            AddressingMode::BuggyIndirect => 2,
        }
    }
}

pub type DecodedInstr = (Instruction, OpInput);

#[derive(Default)]
pub struct Nmos6502;

impl Nmos6502 {
    pub fn decode(opcode: u8) -> Option<(Instruction, AddressingMode)> {
        match opcode {
            0x00 => Some((Instruction::BRK, AddressingMode::IMP)),
            0x01 => Some((Instruction::ORA, AddressingMode::IZX)),
            0x02 => None,
            0x03 => Some((Instruction::SLO, AddressingMode::IZX)),
            0x04 => Some((Instruction::NOP, AddressingMode::ZP0)),
            0x05 => Some((Instruction::ORA, AddressingMode::ZP0)),
            0x06 => Some((Instruction::ASL, AddressingMode::ZP0)),
            0x07 => Some((Instruction::SLO, AddressingMode::ZP0)),
            0x08 => Some((Instruction::PHP, AddressingMode::IMP)),
            0x09 => Some((Instruction::ORA, AddressingMode::IMM)),
            0x0A => Some((Instruction::ASL, AddressingMode::ACC)),
            0x0C => Some((Instruction::NOP, AddressingMode::ABS)),
            0x0D => Some((Instruction::ORA, AddressingMode::ABS)),
            0x0E => Some((Instruction::ASL, AddressingMode::ABS)),
            0x0F => Some((Instruction::SLO, AddressingMode::ABS)),
            0x10 => Some((Instruction::BPL, AddressingMode::REL)),
            0x11 => Some((Instruction::ORA, AddressingMode::IZY)),
            0x13 => Some((Instruction::SLO, AddressingMode::IZY)),
            0x14 => Some((Instruction::NOP, AddressingMode::ABS)),
            0x15 => Some((Instruction::ORA, AddressingMode::ZPX)),
            0x16 => Some((Instruction::ASL, AddressingMode::ZPX)),
            0x17 => Some((Instruction::SLO, AddressingMode::ZPX)),
            0x18 => Some((Instruction::CLC, AddressingMode::IMP)),
            0x19 => Some((Instruction::ORA, AddressingMode::ABY)),
            0x1A => Some((Instruction::NOP, AddressingMode::IMP)),
            0x1B => Some((Instruction::SLO, AddressingMode::ABY)),
            0x1C => Some((Instruction::NOP, AddressingMode::ABS)),
            0x1D => Some((Instruction::ORA, AddressingMode::ABX)),
            0x1E => Some((Instruction::ASL, AddressingMode::ABX)),
            0x1F => Some((Instruction::SLO, AddressingMode::ABX)),
            0x20 => Some((Instruction::JSR, AddressingMode::ABS)),
            0x21 => Some((Instruction::AND, AddressingMode::IZX)),
            0x23 => Some((Instruction::RLA, AddressingMode::IZX)),
            0x24 => Some((Instruction::BIT, AddressingMode::ZP0)),
            0x25 => Some((Instruction::AND, AddressingMode::ZP0)),
            0x26 => Some((Instruction::ROL, AddressingMode::ZP0)),
            0x27 => Some((Instruction::RLA, AddressingMode::ZP0)),
            0x28 => Some((Instruction::PLP, AddressingMode::IMP)),
            0x29 => Some((Instruction::AND, AddressingMode::IMM)),
            0x2A => Some((Instruction::ROL, AddressingMode::ACC)),
            0x2C => Some((Instruction::BIT, AddressingMode::ABS)),
            0x2D => Some((Instruction::AND, AddressingMode::ABS)),
            0x2E => Some((Instruction::ROL, AddressingMode::ABS)),
            0x2F => Some((Instruction::RLA, AddressingMode::ABS)),
            0x30 => Some((Instruction::BMI, AddressingMode::REL)),
            0x31 => Some((Instruction::AND, AddressingMode::IZY)),
            0x33 => Some((Instruction::RLA, AddressingMode::IZY)),
            0x34 => Some((Instruction::DOP, AddressingMode::ZPX)),
            0x35 => Some((Instruction::AND, AddressingMode::ZPX)),
            0x36 => Some((Instruction::ROL, AddressingMode::ZPX)),
            0x37 => Some((Instruction::RLA, AddressingMode::ZPX)),
            0x38 => Some((Instruction::SEC, AddressingMode::IMP)),
            0x39 => Some((Instruction::AND, AddressingMode::ABY)),
            0x3A => Some((Instruction::NOP, AddressingMode::IMP)),
            0x3B => Some((Instruction::RLA, AddressingMode::ABY)),
            0x3C => Some((Instruction::NOP, AddressingMode::ABS)),
            0x3D => Some((Instruction::AND, AddressingMode::ABX)),
            0x3E => Some((Instruction::ROL, AddressingMode::ABX)),
            0x3F => Some((Instruction::RLA, AddressingMode::ABX)),
            0x40 => Some((Instruction::RTI, AddressingMode::IMP)),
            0x41 => Some((Instruction::EOR, AddressingMode::IZX)),
            0x43 => Some((Instruction::SRE, AddressingMode::IZX)),
            0x44 => Some((Instruction::NOP, AddressingMode::ZP0)),
            0x45 => Some((Instruction::EOR, AddressingMode::ZP0)),
            0x46 => Some((Instruction::LSR, AddressingMode::ZP0)),
            0x47 => Some((Instruction::SRE, AddressingMode::ZP0)),
            0x48 => Some((Instruction::PHA, AddressingMode::IMP)),
            0x49 => Some((Instruction::EOR, AddressingMode::IMM)),
            0x4A => Some((Instruction::LSR, AddressingMode::ACC)),
            0x4C => Some((Instruction::JMP, AddressingMode::ABS)),
            0x4D => Some((Instruction::EOR, AddressingMode::ABS)),
            0x4E => Some((Instruction::LSR, AddressingMode::ABS)),
            0x4F => Some((Instruction::SRE, AddressingMode::ABS)),
            0x50 => Some((Instruction::BVC, AddressingMode::REL)),
            0x51 => Some((Instruction::EOR, AddressingMode::IZY)),
            0x52 => Some((Instruction::KIL, AddressingMode::IMP)),
            0x53 => Some((Instruction::SRE, AddressingMode::IZY)),
            0x55 => Some((Instruction::EOR, AddressingMode::ZPX)),
            0x56 => Some((Instruction::LSR, AddressingMode::ZPX)),
            0x57 => Some((Instruction::SRE, AddressingMode::ZPX)),
            0x59 => Some((Instruction::EOR, AddressingMode::ABY)),
            0x5A => Some((Instruction::NOP, AddressingMode::IMP)),
            0x5B => Some((Instruction::SRE, AddressingMode::ABY)),
            0x5C => Some((Instruction::NOP, AddressingMode::ABS)),
            0x5D => Some((Instruction::EOR, AddressingMode::ABX)),
            0x5E => Some((Instruction::LSR, AddressingMode::ABX)),
            0x5F => Some((Instruction::SRE, AddressingMode::ABX)),
            0x60 => Some((Instruction::RTS, AddressingMode::IMP)),
            0x61 => Some((Instruction::ADC, AddressingMode::IZX)),
            0x63 => Some((Instruction::RRA, AddressingMode::IZX)),
            0x64 => Some((Instruction::NOP, AddressingMode::ZP0)),
            0x65 => Some((Instruction::ADC, AddressingMode::ZP0)),
            0x66 => Some((Instruction::ROR, AddressingMode::ZP0)),
            0x67 => Some((Instruction::RRA, AddressingMode::ZP0)),
            0x68 => Some((Instruction::PLA, AddressingMode::IMP)),
            0x69 => Some((Instruction::ADC, AddressingMode::IMM)),
            0x6A => Some((Instruction::ROR, AddressingMode::ACC)),
            0x6C => Some((Instruction::JMP, AddressingMode::BuggyIndirect)),
            0x6D => Some((Instruction::ADC, AddressingMode::ABS)),
            0x6E => Some((Instruction::ROR, AddressingMode::ABS)),
            0x6F => Some((Instruction::RRA, AddressingMode::ABS)),
            0x70 => Some((Instruction::BVS, AddressingMode::REL)),
            0x71 => Some((Instruction::ADC, AddressingMode::IZY)),
            0x73 => Some((Instruction::RRA, AddressingMode::IZY)),
            0x75 => Some((Instruction::ADC, AddressingMode::ZPX)),
            0x76 => Some((Instruction::ROR, AddressingMode::ZPX)),
            0x77 => Some((Instruction::RRA, AddressingMode::ZPX)),
            0x78 => Some((Instruction::SEI, AddressingMode::IMP)),
            0x79 => Some((Instruction::ADC, AddressingMode::ABY)),
            0x7A => Some((Instruction::NOP, AddressingMode::IMP)),
            0x7B => Some((Instruction::RRA, AddressingMode::ABY)),
            0x7C => Some((Instruction::NOP, AddressingMode::ABS)),
            0x7D => Some((Instruction::ADC, AddressingMode::ABX)),
            0x7E => Some((Instruction::ROR, AddressingMode::ABX)),
            0x7F => Some((Instruction::RRA, AddressingMode::ABX)),
            0x80 => Some((Instruction::NOP, AddressingMode::ZP0)),
            0x81 => Some((Instruction::STA, AddressingMode::IZX)),
            0x83 => Some((Instruction::AAX, AddressingMode::IZX)),
            0x84 => Some((Instruction::STY, AddressingMode::ZP0)),
            0x85 => Some((Instruction::STA, AddressingMode::ZP0)),
            0x86 => Some((Instruction::STX, AddressingMode::ZP0)),
            0x87 => Some((Instruction::AAX, AddressingMode::ZP0)),
            0x88 => Some((Instruction::DEY, AddressingMode::IMP)),
            0x8A => Some((Instruction::TXA, AddressingMode::IMP)),
            0x8C => Some((Instruction::STY, AddressingMode::ABS)),
            0x8D => Some((Instruction::STA, AddressingMode::ABS)),
            0x8E => Some((Instruction::STX, AddressingMode::ABS)),
            0x8F => Some((Instruction::AAX, AddressingMode::ABS)),
            0x90 => Some((Instruction::BCC, AddressingMode::REL)),
            0x91 => Some((Instruction::STA, AddressingMode::IZY)),
            0x94 => Some((Instruction::STY, AddressingMode::ZPX)),
            0x95 => Some((Instruction::STA, AddressingMode::ZPX)),
            0x96 => Some((Instruction::STX, AddressingMode::ZPY)),
            0x97 => Some((Instruction::AAX, AddressingMode::ZPY)),
            0x98 => Some((Instruction::TYA, AddressingMode::IMP)),
            0x99 => Some((Instruction::STA, AddressingMode::ABY)),
            0x9A => Some((Instruction::TXS, AddressingMode::IMP)),
            0x9D => Some((Instruction::STA, AddressingMode::ABX)),
            0xA0 => Some((Instruction::LDY, AddressingMode::IMM)),
            0xA1 => Some((Instruction::LDA, AddressingMode::IZX)),
            0xA2 => Some((Instruction::LDX, AddressingMode::IMM)),
            0xA3 => Some((Instruction::LAX, AddressingMode::IZX)),
            0xA4 => Some((Instruction::LDY, AddressingMode::ZP0)),
            0xA5 => Some((Instruction::LDA, AddressingMode::ZP0)),
            0xA6 => Some((Instruction::LDX, AddressingMode::ZP0)),
            0xA7 => Some((Instruction::LAX, AddressingMode::ZP0)),
            0xA8 => Some((Instruction::TAY, AddressingMode::IMP)),
            0xA9 => Some((Instruction::LDA, AddressingMode::IMM)),
            0xAA => Some((Instruction::TAX, AddressingMode::IMP)),
            0xAC => Some((Instruction::LDY, AddressingMode::ABS)),
            0xAD => Some((Instruction::LDA, AddressingMode::ABS)),
            0xAE => Some((Instruction::LDX, AddressingMode::ABS)),
            0xAF => Some((Instruction::LAX, AddressingMode::ABS)),
            0xB0 => Some((Instruction::BCS, AddressingMode::REL)),
            0xB1 => Some((Instruction::LDA, AddressingMode::IZY)),
            0xB3 => Some((Instruction::LAX, AddressingMode::IZY)),
            0xB4 => Some((Instruction::LDY, AddressingMode::ZPX)),
            0xB5 => Some((Instruction::LDA, AddressingMode::ZPX)),
            0xB6 => Some((Instruction::LDX, AddressingMode::ZPY)),
            0xB7 => Some((Instruction::LAX, AddressingMode::ZPY)),
            0xB8 => Some((Instruction::CLV, AddressingMode::IMP)),
            0xB9 => Some((Instruction::LDA, AddressingMode::ABY)),
            0xBA => Some((Instruction::TSX, AddressingMode::IMP)),
            0xBC => Some((Instruction::LDY, AddressingMode::ABX)),
            0xBD => Some((Instruction::LDA, AddressingMode::ABX)),
            0xBE => Some((Instruction::LDX, AddressingMode::ABY)),
            0xBF => Some((Instruction::LAX, AddressingMode::ABY)),
            0xC0 => Some((Instruction::CPY, AddressingMode::IMM)),
            0xC1 => Some((Instruction::CMP, AddressingMode::IZX)),
            0xC3 => Some((Instruction::DCP, AddressingMode::IZX)),
            0xC4 => Some((Instruction::CPY, AddressingMode::ZP0)),
            0xC5 => Some((Instruction::CMP, AddressingMode::ZP0)),
            0xC6 => Some((Instruction::DEC, AddressingMode::ZP0)),
            0xC7 => Some((Instruction::DCP, AddressingMode::ZP0)),
            0xC8 => Some((Instruction::INY, AddressingMode::IMP)),
            0xC9 => Some((Instruction::CMP, AddressingMode::IMM)),
            0xCA => Some((Instruction::DEX, AddressingMode::IMP)),
            0xCC => Some((Instruction::CPY, AddressingMode::ABS)),
            0xCD => Some((Instruction::CMP, AddressingMode::ABS)),
            0xCE => Some((Instruction::DEC, AddressingMode::ABS)),
            0xCF => Some((Instruction::DCP, AddressingMode::ABS)),
            0xD0 => Some((Instruction::BNE, AddressingMode::REL)),
            0xD1 => Some((Instruction::CMP, AddressingMode::IZY)),
            0xD3 => Some((Instruction::DCP, AddressingMode::IZY)),
            0xD5 => Some((Instruction::CMP, AddressingMode::ZPX)),
            0xD6 => Some((Instruction::DEC, AddressingMode::ZPX)),
            0xD7 => Some((Instruction::DCP, AddressingMode::ZPX)),
            0xD8 => Some((Instruction::CLD, AddressingMode::IMP)),
            0xD9 => Some((Instruction::CMP, AddressingMode::ABY)),
            0xDA => Some((Instruction::NOP, AddressingMode::IMP)),
            0xDB => Some((Instruction::DCP, AddressingMode::ABY)),
            0xDC => Some((Instruction::NOP, AddressingMode::ABS)),
            0xDD => Some((Instruction::CMP, AddressingMode::ABX)),
            0xDE => Some((Instruction::DEC, AddressingMode::ABX)),
            0xDF => Some((Instruction::DCP, AddressingMode::ABX)),
            0xE0 => Some((Instruction::CPX, AddressingMode::IMM)),
            0xE1 => Some((Instruction::SBC, AddressingMode::IZX)),
            0xE3 => Some((Instruction::ISC, AddressingMode::IZX)),
            0xE4 => Some((Instruction::CPX, AddressingMode::ZP0)),
            0xE5 => Some((Instruction::SBC, AddressingMode::ZP0)),
            0xE6 => Some((Instruction::INC, AddressingMode::ZP0)),
            0xE7 => Some((Instruction::ISC, AddressingMode::ZP0)),
            0xE8 => Some((Instruction::INX, AddressingMode::IMP)),
            0xE9 => Some((Instruction::SBC, AddressingMode::IMM)),
            0xEA => Some((Instruction::NOP, AddressingMode::IMP)),
            0xEB => Some((Instruction::SBC, AddressingMode::IMM)),
            0xEC => Some((Instruction::CPX, AddressingMode::ABS)),
            0xED => Some((Instruction::SBC, AddressingMode::ABS)),
            0xEE => Some((Instruction::INC, AddressingMode::ABS)),
            0xEF => Some((Instruction::ISC, AddressingMode::ABS)),
            0xF0 => Some((Instruction::BEQ, AddressingMode::REL)),
            0xF1 => Some((Instruction::SBC, AddressingMode::IZY)),
            0xF3 => Some((Instruction::ISC, AddressingMode::IZY)),
            0xF5 => Some((Instruction::SBC, AddressingMode::ZPX)),
            0xF6 => Some((Instruction::INC, AddressingMode::ZPX)),
            0xF7 => Some((Instruction::ISC, AddressingMode::ZPX)),
            0xF8 => Some((Instruction::SED, AddressingMode::IMP)),
            0xF9 => Some((Instruction::SBC, AddressingMode::ABY)),
            0xFA => Some((Instruction::NOP, AddressingMode::IMP)),
            0xFB => Some((Instruction::ISC, AddressingMode::ABY)),
            0xFC => Some((Instruction::NOP, AddressingMode::ABS)),
            0xFD => Some((Instruction::SBC, AddressingMode::ABX)),
            0xFE => Some((Instruction::INC, AddressingMode::ABX)),
            0xFF => Some((Instruction::ISC, AddressingMode::ABX)),
            x => panic!("FAIL decode {:X}", x),
        }
    }
}
